env: foraging

env_args:
  field_size: 10
  players: 4
  max_food: 2
  #max_num_food: 2
  #min_player_level: 1
  #min_food_level: 1
  #max_food_level: 3
  force_coop: False
  partially_observe: True
  sight: 2
  is_print: False
  seed: 0
  need_render: False

learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 2050000
test_interval: 10000
test_nepisode: 40
