# --- Defaults for 4x4 predator prey, 4 agent capture, walls ---

env: "pursuit"

env_args:
    seed: 0

test_greedy: True
test_nepisode: 16
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 20500000000000000000000000000000000000000000000000000
obs_agent_id: False
